name: Lint Code

on:
  push:
    branches-ignore:
      - main
      - development
      - staging
  pull_request:
    branches-ignore:
      - main
      - development
      - staging

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: ['20.11.1']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm all-lint
